name: Build and release container image

on:
  push:
    branches-ignore:
      - 'main'

env:
  # Some Cloud provider env vars
  CSP_CONTAINER_REGISTRY: docker.io://achapusot
  APP_NAME: demo-app

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-ref: ${{ steps.set_image_ref.outputs.image_ref }}
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Generate the image tag with shorten SHA
        id: generate_tag
        run: echo "image_tag=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Set image ref
        id: set_image_ref
        run: echo "image_ref=${{ env.CSP_CONTAINER_REGISTRY }}/${{ env.APP_NAME }}:${{ steps.generate_tag.outputs.image_tag }}" >> $GITHUB_OUTPUT

      - name: Docker build
        run: |
          echo "docker build . -t ${{ steps.set_image_ref.outputs.image_ref }}"

  vulnerability-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@0.24.0
      #   with:
      #     image-ref: '${{ needs.build.outputs.image-ref }}'
      #     format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'CRITICAL,HIGH'
      - name: Run Trivy vulnerability scanner
        run: |
          echo "trivy checks ${{ needs.build.outputs.image-ref }}"

  push-on-registry:
    runs-on: ubuntu-latest
    needs:
      - build
      - vulnerability-scan
    steps:
      - name: Docker push
        run: |
          echo "docker push ${{ needs.build.outputs.image-ref }}"
